{% set name = "hklpy" %}
{% set version = "1.1.0rc2" %}
{% set sha256 = "6c912b23c350fba20a60161152bf85f2019e8a93d257bd8fa01d3c46cd5313d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [python_impl == 'pypy']
  skip: true  # [py<38 or win or osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - apischema
    - databroker
    - hkl
    - numpy
    - ophyd
    - pandas
    - pint
    - pygobject
    - pyresttable
    - spec2nexus
    - tqdm

test:
  imports:
    - hkl
    - hkl.calc
    - hkl.context
    - hkl.diffract
    - hkl.engine
    - hkl.sample
    - hkl.util

about:
  home: https://github.com/bluesky/hklpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffractometer computation library with ophyd pseudopositioner support
  doc_url: http://blueskyproject.io/hklpy
  dev_url: https://github.com/bluesky/hklpy

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
    - kbeeperez
