{% set name = "hklpy" %}
{% set version = "1.0.2" %}
{% set sha256 = "7eee5ac5c5b5d4f032ef38d9a4697599629042af01a0873ca57811b1e4dc6746" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37 or win or osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - hkl
    - numpy
    - ophyd
    - pandas
    - pint
    - pygobject
    - pyresttable

test:
  imports:
    - hkl
    - hkl.calc
    - hkl.context
    - hkl.diffract
    - hkl.engine
    - hkl.sample
    - hkl.util

about:
  home: https://github.com/bluesky/hklpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffractometer computation library with ophyd pseudopositioner support
  doc_url: http://blueskyproject.io/hklpy
  dev_url: https://github.com/bluesky/hklpy

extra:
  recipe-maintainers:
    - mrakitin
    - prjemian
    - kbeeperez
